services:
  - type: web
    name: argus-qa
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn callcenter_qa.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
    healthCheckPath: /

